on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run test:node
        env:
          CI: true
